# Generated by Django 3.1 on 2022-01-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodgram', '0001_initial'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ManyToManyField(blank=True, related_name='shoppingcart_recipe', to='foodgram.Recipe', verbose_name='Рецепт'),
        ),
    ]
